version: '3.1'

services:
  node:
    container_name: srnstreamer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "49161:3000"
    volumes:
      - /app/node_modules
      - ./upload:/app/upload
      - ./uploads:/app/uploads
    environment:
      - REDIS_HOST=redis
      - MONGODB_URI=mongodb://admin:password@srnstreamer-mongo:27017/srnstreamer
    depends_on:
      - redis
      - mongo
    command: npm start
    networks:
      - srnstreamer-network

  mongo:
    container_name: srnstreamer-mongo
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/db:/data/db
    ports:
      - "27011:27017"
    networks:
      - srnstreamer-network
  
  mongo-express:
    container_name: srnstreamer-mongo-express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@srnstreamer-mongo:27017/srnstreamer
    networks:
      - srnstreamer-network

  redis:
    container_name: srnstreamer-redis
    image: redis
    networks:
      - srnstreamer-network

networks:
  srnstreamer-network:
    driver: bridge
